services:
  fastapi:
    build: .
    container_name: sentiment-api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./mlruns:/app/mlruns

  streamlit:
    build: .
    container_name: sentiment-ui
    command: streamlit run app/ui.py --server.port 8501 --server.address 0.0.0.0
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app/app
    networks:
      - sentiment-network

networks:
  sentiment-network:
    driver: bridge
